name: Selenium Scraper

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install selenium browsermob-proxy

      - name: Install Google Chrome Stable
        run: |
          # Install necessary dependencies
          sudo apt-get update
          sudo apt-get install -y wget curl unzip

          # Install the stable version of Google Chrome
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver for the Installed Chrome Version
        run: |
          # Find the installed Chrome version
          CHROME_VERSION=$(google-chrome-stable --version | sed 's/Google Chrome //')
          
          # Install ChromeDriver corresponding to the installed Chrome version
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install BrowserMob Proxy
        run: |
          # Install BrowserMob Proxy
          wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip
          unzip browsermob-proxy-2.1.4-bin.zip
          sudo mv browsermob-proxy-2.1.4 /usr/local/bin/browsermob-proxy
          sudo chmod +x /usr/local/bin/browsermob-proxy

      - name: Debug Information
        run: |
          echo "Running as $(whoami)"
          echo "Python version: $(python --version)"
          echo "Google Chrome version: $(google-chrome-stable --version)"
          echo "ChromeDriver version: $(chromedriver --version)"
          ls -l /usr/local/bin
          ls -l /home/runner/
          curl --version

      - name: Run Selenium Script
        run: python scripts/script.py

      - name: Upload Result (JSON Output)
        uses: actions/upload-artifact@v3
        with:
          name: soccer-links-json
          path: scripts/soccer_links.json
